#!/usr/bin/env python2.6

###
### use to filter cases
### regression name: c,cp,j,jp,o,op
### Author: junyue

excludes=['bug217660_xiaochu', 'collect','trx_collect', 'ps_cache'] 

c_list=['ps_affect_rows', 
        'affect_rows', 
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
	'jdbc_replace',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        ] + excludes

cp_list=['ps_affect_rows', 
        'affect_rows', 
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'special_hook',
        'set',
        'build_in_func_test',
        'kill',
        'killquery',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
	'jdbc_replace',
	'jdbc_replace_trx',
        ] + excludes

j_list=['ps_1', 
        'ps_3', 
        'select_error', 
        'autocommit', 
        'trx_timeout',
        'trx_1',
        'trx_2',
        'trx_3',
        'trx_4',
        'trx_5',
        'trx_basic',
        'empty_input',
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'set',
        'serialize_6k_bug',
        'kill',
        'killquery',
        ] + excludes
jp_list=['ps_1', 
        'ps_3', 
        'select_error', 
        'autocommit', 
        'trx_timeout',
        'trx_1',
        'trx_2',
        'trx_3',
        'trx_4',
        'trx_5',
        'trx_basic',
        'empty_input',
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'set',
        'many_columns',
        'build_in_func_test',
        'serialize_6k_bug',
        'kill',
        'killquery',
        ] + excludes

o_list=['ps_affect_rows', 
        'affect_rows', 
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'create_use',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
	'set',
	'jdbc_replace',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'create_user',
        ] + excludes

op_list=['ps_affect_rows', 
        'affect_rows', 
        'master_ups_lost_causedby_switch_twice', 
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'build_in_func_test',
        'create_user',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
	'set',
	'jdbc_replace',
	'jdbc_replace_parallel_trx',
        'create_user',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
        ] + excludes
